### ISSUE TITLE
Support for Playwright

### ISSUE THREAD

**Issue by whizzzkid** [buildkite/test-collector-javascript#67] opened 2023-09-22 17:25 UTC
Playwright Supports Reporters: https://playwright.dev/docs/test-reporters#custom-reporters

It would be nice to have test-analytics around those.

**Comment by mitchwd** [comment] 2023-09-27 05:48
FYI: this is a duplicate of https://github.com/buildkite/test-collector-javascript/issues/41

**Closed** 2023-10-05 22:53 UTC
